src/server/basketball-mgmt/src/main/java/com/renyi/basketball/mgmt/controller/LeagueController.java
package com.renyi.basketball.mgmt.controller;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.renyi.basketball.bussness.common.LeagueStatus;
import com.renyi.basketball.bussness.common.ViewData;
import com.renyi.basketball.bussness.constants.ApiConstants;
import com.renyi.basketball.bussness.dto.LeagueCountCache;
import com.renyi.basketball.bussness.dto.LeagueInfoDto;
import com.renyi.basketball.bussness.exception.BusinessException;
import com.renyi.basketball.bussness.po.Admin;
import com.renyi.basketball.bussness.po.League;
import com.renyi.basketball.bussness.po.LeagueInfo;
import com.renyi.basketball.bussness.po.Match;
import com.renyi.basketball.bussness.po.Team;
import com.renyi.basketball.bussness.po.Venue;
import com.renyi.basketball.bussness.service.LeagueInfoService;
import com.renyi.basketball.bussness.service.LeagueService;
import com.renyi.basketball.bussness.service.LeagueStageService;
import com.renyi.basketball.bussness.service.MatchService;
import com.renyi.basketball.bussness.service.TeamService;
import com.renyi.basketball.bussness.service.VenueService;

import cn.magicbeans.pagination.Page;
import cn.magicbeans.pagination.Pageable;
import jersey.repackaged.com.google.common.collect.Lists;

@Controller
@RequestMapping("/league")
public class LeagueController extends BaseAdminController {
	@Resource
	private TeamService teamService;
	@Resource
	private LeagueService leagueService;
	@Resource
	private VenueService venueService;
	@Resource
	private MatchService matchService;
	@Resource
	private LeagueInfoService leagueInfoService;
	@Resource
	private LeagueStageService leagueStageService;
	
	/**
	 * 赛事列表
	 * 
	 * @param
	 * @return
	 */
	@RequestMapping("/list")
	public String list() {
		return "/league/list";
	}
	
	/**
	 * 前往添加赛事页面
	 * 
	 * @return
	 */
	@RequestMapping("/add")
	public String add(ModelMap map) {
		map.put("stageList", leagueStageService.queryAll());
		return "/league/add";
	}
	
	@RequestMapping("/season")
	public String season(ModelMap map, Long id) {
		map.put("leagueId", id);
		return "/season/list";
	}
	
	@RequestMapping("/division")
	public String division(ModelMap map, Long id) {
		map.put("leagueId", id);
		return "/division/list";
	}

	/**
	 * 获取赛事列表分页
	 * 
	 * @param request
	 * @param pageable
	 * @param name
	 * @param status
	 * @return
	 */
	@RequestMapping("/leagueList")
	@ResponseBody
	public ViewData leagueList(HttpServletRequest request, Pageable pageable, String name, Integer status) {
		Admin admin = getCurrent(request);
		if (admin == null) {
			return buildFailureJson(ApiConstants.FAIL, "请登录!");
		}
		if (Admin.ARENAS_ADMIN == admin.getType()) {
			return buildFailureJson(ApiConstants.FAIL, "无权限!");
		}
		try {
			Long companyId = null;
			if (Admin.COMPANY_ADMIN == admin.getType()) {
				companyId = admin.getCompanyId();
			}
			List<Integer> chooseStatus = new ArrayList<Integer>();
			if (status == null) {
				chooseStatus.add(LeagueStatus.end.code());// 比赛结束
				chooseStatus.add(LeagueStatus.gaming.code());// 比赛中
				chooseStatus.add(LeagueStatus.signend.code());// 报名截止
				chooseStatus.add(LeagueStatus.signing.code());// 报名中
				chooseStatus.add(LeagueStatus.not_through.code());// 未通过
				chooseStatus.add(LeagueStatus.wait_through.code());// 待审核
			} else {
				chooseStatus.add(status);
			}
			Page<League> page = leagueService.query(name, chooseStatus, pageable, companyId);
			return buildSuccessJson(ApiConstants.SUCCESS, "成功", page);
		} catch (Exception b) {
			logger.error(b);
			return buildFailureJson(ViewData.FlagEnum.ERROR, ApiConstants.FAIL, "异常");
		}

	}

	/**
	 * 添加赛事
	 * 
	 * @param
	 * @param
	 * @return
	 */
	@RequestMapping(value = "/save", method = RequestMethod.POST)
	public String save(League league, HttpServletRequest request, ModelMap map) {
		Admin admin = getCurrent(request);
		if (admin == null) {
			return "redirect:/login.jsp";
		}
		try {
			league.setStatus(LeagueStatus.signing.code());
			leagueService.save(league);
			map.put("msg", "添加赛事成功,等待审核!");
		} catch (BusinessException e) {
			logger.error(e);
			map.put("msg", "添加赛事异常");
		}

		return "/league/list";
	}

	/**
	 * 获得队伍列表
	 * 
	 * @return
	 */
	@RequestMapping("/getTeams")
	@ResponseBody
	public List<Team> getTeams() {
		return teamService.queryAll();
	}
	
	@RequestMapping("/getVenues")
	@ResponseBody
	public List<Venue> getVenues(HttpServletRequest request) {
		try {
			Admin admin = getCurrent(request);
			if (admin == null) {
				return null;
			}
			if (Admin.COMPANY_ADMIN == admin.getType()) {
				Map<String, Object> params = new HashMap<String, Object>();
				params.put("company_id", admin.getCompanyId());
				return venueService.find(params);
			} else if (Admin.SUPER_ADMIN == admin.getType()) {
				return venueService.findAll();
			}
			return null;
		} catch (BusinessException e) {
			logger.error(e.getMessage(), e);
			return null;
		}
	}

	/**
	 * 去详情页面
	 * 
	 * @param id
	 * @param map
	 * @return
	 */
	@RequestMapping("/detail")
	public String detailPage(Long id, ModelMap map) {
		List<Match> matchs = null;
		League league = null;
		try {
			matchs = matchService.queryLeagueMatch(id);
			league = leagueService.queryById(id);
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
		}
		map.put("matches", matchs);
		map.put("league", league);
		return "/league/detail";
	}

	/**
	 * 去统计页面
	 * 
	 * @param id
	 * @param map
	 * @return
	 */
	@RequestMapping("/count")
	public String countPage(Long id, ModelMap map) {
		try {
			LeagueCountCache leagueCount = leagueService.queryLeagueBang(id);
			if (leagueCount != null) {
				map.put("leagueBang", leagueCount);
			}
		} catch (BusinessException e) {
			logger.error(e.getMessage(), e);
		}
		return "/league/count";
	}

	/**
	 * 去动态列表页面
	 * 
	 * @return
	 */
	@RequestMapping("/publishList")
	public String publishListPage(Integer leagueId, ModelMap map) {
		map.put("leagueId", leagueId);
		return "/league/publishList";
	}

	/**
	 * 去发布动态页面
	 * 
	 * @return
	 */
	@RequestMapping("/publish")
	public String publishPage(Integer leagueId, ModelMap map) {
		map.put("leagueId", leagueId);
		return "/league/publish";
	}

	/**
	 * 添加动态
	 * 
	 * @param pushImgs
	 * @param content
	 * @param leagueId
	 * @param map
	 * @return
	 */
	@RequestMapping("/saveInfo")
	public String saveInfo(String[] pushImgs, String content, Long leagueId, ModelMap map) {
		if (leagueId == null) {
			map.put("msg", "请选择赛事");
		} else {
			try {
				LeagueInfo info = new LeagueInfo();
				info.setContent(content);
				info.setImgUrls(Arrays.asList(pushImgs));
				info.setLeagueId(leagueId.intValue());
				leagueInfoService.save(info);
				map.put("msg", "发布动态成功");
			} catch (BusinessException e) {
				map.put("msg", "发布动态异常");
				logger.error(e.getMessage(), e);
			}
			map.put("leagueId", leagueId);
		}

		return "/league/publishList";
	}

	/**
	 * 获得赛事动态列表
	 * 
	 * @param leagueId
	 * @param pageable
	 * @return
	 */
	@RequestMapping("/getLeagueInfo")
	@ResponseBody
	public ViewData getLeagueInfo(Long leagueId, Pageable pageable) {
		if (leagueId == null) {
			return buildSuccessCodeJson(ApiConstants.FIELD_NOT_NULL, "参数不足");
		}
		try {
			Page<LeagueInfoDto> infos = leagueInfoService.queryInfoByLeagueId(leagueId, pageable);
			return buildSuccessJson(ApiConstants.SUCCESS, "获取列表成功", infos);
		} catch (BusinessException e) {
			logger.error(e.getMessage(), e);
			return buildFailureJson(ViewData.FlagEnum.ERROR, ApiConstants.FAIL, "获取动态列表异常");
		}
	}
	
	/**
	 * 获得赛事
	 * 
	 * @param leagueId
	 * @param pageable
	 * @return
	 */
	@RequestMapping("/getLeague")
	@ResponseBody
	public ViewData getLeague(Long leagueId) {
		if (leagueId == null) {
			return buildFailureJson(ApiConstants.FIELD_NOT_NULL, "参数不足");
		}
		try {
			League league = leagueService.queryById(leagueId);
			return buildSuccessJson(ApiConstants.SUCCESS, "获取赛事成功", league);
		} catch (BusinessException e) {
			logger.error(e.getMessage(), e);
			return buildFailureJson(ViewData.FlagEnum.ERROR, ApiConstants.FAIL, "获取动态列表异常");
		}
	}
	
	/**
	 * 获得所有赛事
	 * 
	 * @return
	 */
	@RequestMapping("/getAll")
	@ResponseBody
	public List<League> getAllLeague() {
		try {
			List<League> leagues = leagueService.findAll();
			return leagues;
		} catch (BusinessException e) {
			logger.error(e.getMessage(), e);
			return Lists.newArrayList();
		}
	}

	/**
	 * 去审核赛事页面
	 * 
	 * @param id
	 * @param map
	 * @return
	 */
	@RequestMapping("/check")
	public String checkPage(Long id, ModelMap map, HttpServletRequest request) {
		Admin admin = getCurrent(request);
		if (admin == null) {
			return "redirect:/login.jsp";
		}
		if (Admin.SUPER_ADMIN != admin.getType()) {
			map.put("msg", "权限不足");
			return "/league/list";
		}
		League league = leagueService.queryById(id);
		map.put("league", league);
		return "/league/check";
	}

	/**
	 * 审核结果
	 * 
	 * @param id
	 * @param request
	 * @param result
	 * @param judgment
	 * @return
	 */
	@RequestMapping("/checkLeague")
	public String checkLeague(Long id, HttpServletRequest request, Integer result, String judgment, ModelMap map) {
		if (id == null || result == null) {
			map.put("msg", "参数不足，审核失败");
			return "/league/list";
		}
		Admin admin = getCurrent(request);
		if (admin == null) {
			return "redirect:/login.jsp";
		}
		if (Admin.SUPER_ADMIN != admin.getType()) {
			map.put("msg", "权限不足");
			return "/league/list";
		}
		try {
			League league = leagueService.find(id);
			if (result == 1) {// 审核通过---报名中状态
				league.setStatus(LeagueStatus.signing.code());
			} else if (result == 0) {// 审核未通过

src/server/basketball-mgmt/src/main/webapp/WEB-INF/view/player/add.jsp
<%@ page import="com.renyi.basketball.bussness.po.Admin" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page isELIgnored="false" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%
    String base = request.getContextPath();
    Admin admin = (Admin)request.getSession().getAttribute(Admin.SESSION_ADMIN);
%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- Head -->
<head>
    <meta charset="utf-8" />
    <title></title>

    <meta name="description" content="Dashboard" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="../../resource/assets/img/favicon.png" type="image/x-icon">

    <!--Basic Styles-->
    <link href="../../resource/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link id="bootstrap-rtl-link" href="" rel="stylesheet" />
    <link href="../../resource/assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="../../resource/assets/css/weather-icons.min.css" rel="stylesheet" />

    <!--Fonts-->

    <!--Beyond styles-->
    <link href="../../resource/assets/css/beyond.min.css" rel="stylesheet" type="text/css" />
    <link href="../../resource/assets/css/demo.min.css" rel="stylesheet" />
    <link href="../../resource/assets/css/typicons.min.css" rel="stylesheet" />
    <link href="../../resource/assets/css/animate.min.css" rel="stylesheet" />
    <link href="../../resource/assets/css/skins/deepblue.min.css" rel="stylesheet" type="text/css" />
    <link href="../../resource/css/common.css" rel="stylesheet" />
    <script src="../../resource/assets/js/skins.min.js"></script>

    <link href="../../resource/fileupload/css/fileinput.css"  rel="stylesheet" type="text/css" />

    <style>
        #filePath{
            box-shadow: none !important;
            -webkit-box-shadow: none !important;
            background: #EEEEEE;
        }
    </style>

</head>
<!-- /Head -->
<!-- Body -->
<body>
<div class="page-breadcrumbs">
    <ul class="breadcrumb">
        <li><a href="">首页</a></li>
        <li class="active">添加球员</li>
    </ul>
</div>
<div class="header-title">
    <h1>
        球员
        <small>
            Player
        </small>
    </h1>
</div>
<div class="page-body">
    <div class="widget">
        <div class="widget-header ">
            <span class="widget-caption">添加球员</span>
        </div>
        <div class="widget-body">
            <div id="registration-form">
                <form role="form" action="save" method="post">
                    <%--<div class="form-group">--%>
                        <%--<label>头像</label>--%>
                        <%--<div>--%>
                            <%--<input id="headUpload" name="res" type="file" class="file-loading" >--%>
                        <%--</div>--%>
                            <%--<span class="input-icon icon-right">--%>
                            	<%--<div class="input-group" style="margin-top: 5px;">--%>
                            		 <%--<span class="input-group-addon">--%>
                                        <%--<i class="fa fa-laptop"></i>--%>
                                    <%--</span>--%>
                                    <%--<input type="hidden" id="filePath" type="text" name="avatar" />--%>
                                <%--</div>--%>
                            <%--</span>--%>
                    <%--</div>--%>
                    <div class="form-group">
                        <label>手机号码</label>
                            <span class="input-icon icon-right">
                            	<div class="spinner">
                                    <div class="input-group">
	                            		 <span class="input-group-addon">
	                                        <i class="fa fa-laptop"></i>
	                                    </span>
                                        <input class="form-control" name="mobile" id="phone" type="text" maxlength="20"  />
                                    </div>
                                </div>
                            </span>
                    </div>
                    <div class="form-group">
                        <label>姓名</label>
                            <span class="input-icon icon-right">
                            	<div class="input-group">
                            		 <span class="input-group-addon">
                                        <i class="fa fa-laptop"></i>
                                    </span>
                                    <input class="form-control" id="name" name="name" type="text" maxlength="20">
                                </div>
                            </span>
                    </div>
                    <div class="form-group">
                        <label>身份证号码</label>
                            <span class="input-icon icon-right">
                            	<div class="input-group">
                            		 <span class="input-group-addon">
                                        <i class="fa fa-laptop"></i>
                                    </span>
                                    <input class="form-control" id="idcard" name="idcard" type="text" maxlength="20">
                                </div>
                            </span>
                    </div>
                    <div class="form-group">
                        <label>密码</label>
                            <span class="input-icon icon-right">
                            	<div class="input-group">
                            		 <span class="input-group-addon">
                                        <i class="fa fa-laptop"></i>
                                    </span>
                                    <input class="form-control" id="pwd" name="pwd" type="text" maxlength="20">
                                </div>
                            </span>
                    </div>
                    <div class="form-group">
                        <label>身高(cm)</label>
                            <span class="input-icon icon-right">
                            	<div class="spinner">
                                    <div class="input-group">
	                            		 <span class="input-group-addon">
	                                        <i class="fa fa-laptop"></i>
	                                    </span>
                                        <input class="form-control spinner-input" name="height" id="height" type="text" maxlength="5">
                                    </div>
                                </div>
                            </span>
                    </div>
                    <div class="form-group">
                        <label>体重（Kg）</label>
                            <span class="input-icon icon-right">
                            	<div class="spinner">
                                    <div class="input-group">
	                            		 <span class="input-group-addon">
	                                        <i class="fa fa-laptop"></i>
	                                    </span>
                                        <input class="form-control spinner-input" name="weight" id="weight" type="text" maxlength="5">
                                    </div>
                                </div>
                            </span>
                    </div>
                    <div class="form-group">
                        <label>年龄</label>
                            <span class="input-icon icon-right">
                            	<div class="spinner">
                                    <div class="input-group">
	                            		 <span class="input-group-addon">
	                                        <i class="fa fa-laptop"></i>
	                                    </span>
                                        <input class="form-control spinner-input" name="age" id="age" type="text" maxlength="3">
                                    </div>
                                </div>
                            </span>
                    </div>
                    <div class="form-group">
                            <span class="input-icon icon-right">
                            	<div class="checkbox">
                                    <label>
                                        <%--<input type="checkbox" checked="checked" value="1" name="isSendMessage">是否发送短信通知--%>
                                        <input type="checkbox"  value="0" name="isSendMessage">是否发送短信通知
                                    </label>
                                </div>
                            </span>
                    </div>
                    <input type="submit" target="iframe"  id="confirmBtn" class="btn btn-info" value="确认" />
                </form>
            </div>
        </div>
    </div>
</div>

<!--Basic Scripts-->
<script src="../../resource/assets/js/jquery-2.0.3.min.js"></script>
<script src="../../resource/assets/js/bootstrap.min.js"></script>

<!--Beyond Scripts-->
<script src="../../resource/assets/js/beyond.min.js"></script>
<!--Page Related Scripts-->

<!--Fuelux Spinner-->
<script src="../../resource/assets/js/fuelux/spinner/fuelux.spinner.min.js"></script>

<script src="../../resource/assets/js/toastr/toastr.js"></script>
<!--Common Scripts -->
<script src="../../resource/js/common.js"></script>
<script src="../../resource/laydate/laydate.js"></script>

<script src="../../resource/fileupload/js/fileinput.js" type="text/javascript"></script>
<script src="../../resource/fileupload/js/fileinput_locale_zh.js" type="text/javascript"></script>
<script>
    <%--$("#headUpload").fileinput({--%>
        <%--language:'zh',--%>
        <%--uploadUrl: '<%=base%>/ctl/resource/upload',// 图片上传接口--%>
        <%--showPreview : true,--%>
        <%--showRemove: false,--%>
        <%--maxFileSize : 2048,  //上传图片的最大限制  50KB--%>
        <%--allowedFileExtensions: ["jpg", "png", "gif","jpeg","bmp"],--%>
        <%--initialCaption: "请选择球员头像"--%>
    <%--});--%>
    <%--$("#headUpload").on("fileuploaded", function (event, data, previewId, index) {--%>
        <%--if (null != data) {--%>
            <%--fillPath = data.response.data;--%>
            <%--$("#filePath").val(fillPath);--%>
        <%--} else {--%>
            <%--Notify("上传失败", 'top-right', '5000', 'danger', 'fa-desktop', true);--%>
        <%--}--%>
    <%--});--%>

    $("#phone").blur(function(){
        $.get("../user/mobileExists",{
            mobile:$("#phone").val()
        },function(json){
            if (json) {
                Notify("该手机号码已注册，请重新输入!", 'top-right', '5000', 'danger', 'fa-desktop', true);
            }
        })
    })

    $('.spinner').spinner();

    $('#confirmBtn').click(function(){
        var phonePattern = /0?(13|14|15|18)[0-9]{9}/;
        var numPattern = /[0-9]+/;
        var phone = $("#phone").val();
        var idcard = $("#idcard").val();
        var name = $("#name").val();
        var pwd = $("#pwd").val();
        var height = $("#height").val();
        var weight = $("#weight").val();
        var age = $("#age").val();
        var avatar = $("#filePath").val();
//        if(avatar ==""){
//            Notify("请上传球员头像", 'top-right', '5000', 'danger', 'fa-desktop', true);
//            return false;
//        }
        if(phone ==""){
            Notify("请填写手机号码", 'top-right', '5000', 'danger', 'fa-desktop', true);
            return false;
        } else if(!phonePattern.test(phone)){
            Notify("手机格式不正确", 'top-right', '5000', 'danger', 'fa-desktop', true);
            return false;
        }
        if(name ==""){
            Notify("请填写球员名字", 'top-right', '5000', 'danger', 'fa-desktop', true);
            return false;
        }
//        if(idcard ==""){
//            Notify("请填写身份证号码", 'top-right', '5000', 'danger', 'fa-desktop', true);
//            return false;
//        }else if(!numPattern.test(idcard)){
//            Notify("身份证号码输入错误，请输入数字", 'top-right', '5000', 'danger', 'fa-desktop', true);
//            return false;
//        }
        if(pwd ==""){
            Notify("请填写密码", 'top-right', '5000', 'danger', 'fa-desktop', true);
            return false;
        }
//        if(height ==""){
//            Notify("请填写球员身高", 'top-right', '5000', 'danger', 'fa-desktop', true);
//            return false;
//        }else if(!numPattern.test(height)){
//            Notify("身高输入错误，请输入数字", 'top-right', '5000', 'danger', 'fa-desktop', true);
//            return false;
//        }
//        if(weight ==""){
//            Notify("请填写球员体重", 'top-right', '5000', 'danger', 'fa-desktop', true);
//            return false;
//        }else if(!numPattern.test(weight)){
//            Notify("体重输入错误，请输入数字", 'top-right', '5000', 'danger', 'fa-desktop', true);
//            return false;
//        }
//        if(age ==""){
//            Notify("请填写球员年龄", 'top-right', '5000', 'danger', 'fa-desktop', true);
//            return false;
//        }else if(!numPattern.test(age)){
//            Notify("年龄输入错误，请输入数字", 'top-right', '5000', 'danger', 'fa-desktop', true);
//            return false;
//        }
    })
</script>
</body>
<!--  /Body -->
</html>

src/server/basketball-mgmt/src/main/webapp/WEB-INF/view/player/detail.jsp
<%@ page import="com.renyi.basketball.bussness.po.Admin" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page isELIgnored="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%
    String base = request.getContextPath();
    //当前管理员类型
    Admin admin = (Admin)request.getSession().getAttribute(Admin.SESSION_ADMIN);
%>
<!DOCTYPE html>
<!--
BeyondAdmin - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.2.0
Version: 1.0.0
Purchase: http://wrapbootstrap.com
-->

<html xmlns="http://www.w3.org/1999/xhtml">
<!-- Head -->
<head>
    <meta charset="utf-8" />
    <title></title>

    <meta name="description" content="Dashboard" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="../../resource/assets/img/favicon.png" type="image/x-icon">

    <!--Basic Styles-->
    <link href="../../resource/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link id="bootstrap-rtl-link" href="" rel="stylesheet" />
    <link href="../../resource/assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="../../resource/assets/css/weather-icons.min.css" rel="stylesheet" />

    <!--Fonts-->

    <!--Beyond styles-->
    <link href="../../resource/assets/css/beyond.min.css" rel="stylesheet" type="text/css" />
    <link href="../../resource/assets/css/demo.min.css" rel="stylesheet" />
    <link href="../../resource/assets/css/typicons.min.css" rel="stylesheet" />
    <link href="../../resource/assets/css/animate.min.css" rel="stylesheet" />
    <link href="../../resource/assets/css/skins/deepblue.min.css" rel="stylesheet" type="text/css" />

    <link href="../../resource/css/common.css" rel="stylesheet" />
    <script src="../../resource/assets/js/skins.min.js"></script>


</head>
<!-- /Head -->
<!-- Body -->
<body>
<div class="page-breadcrumbs">
    <ul class="breadcrumb">
        <li><a href="">首页</a></li>
        <li class="active">球员详情</li>
    </ul>
</div>
<div class="header-title">
    <h1>
        球员
        <small>
            Player
        </small>
    </h1>
</div>
<span style="text-align: center;color: red;font-weight: 600">${msg}</span>
<div class="page-body">
    <div class="widget">
        <div class="widget-header ">
            <span class="widget-caption">球员详情</span>
        </div>
        <div class="widget-body">
            <div class="box-body">
                <div align="center">
                    <h2>球员 ${player.name}</h2>
                </div>

                <%--<div class="form-group">--%>
                    <%--<label>密码</label>--%>
                    <%--<label>${player.}</label>--%>
                    <%--<img src="">--%>
                <%--</div>--%>

                <div class="form-group">
                    <label>球员头像</label>
                    <img src="${player.avatar}">
                </div>

                <div class="form-group">
                    <label>所属球队</label>
                    <label>
                        <c:forEach items="${player.teams}" var="team">
                            ${team.name}
                        </c:forEach>
                    </label>
                </div>

                <%--<div class="form-group">--%>
                    <%--<label>队长</label>--%>
                    <%--<label></label>--%>
                <%--</div>--%>

                <div class="form-group">
                    <label>手机</label>
                    <label>${player.mobile}</label>
                </div>


                <div class="form-group">
                    <label>身高</label>
                    <label>${player.height}</label>
                </div>

                <div class="form-group">
                    <label>体重</label>
                    <label>${player.weight}</label>
                </div>


                <div class="form-group">
                    <label>年龄</label>
                    <label>${player.age}</label>
                </div>

                <%--<div class="form-group">--%>
                    <%--<label>记分员证书</label>--%>
                    <%--<img src="http://.9026.com/api/avatar/avatar.png">--%>
                <%--</div>--%>

                <div align="center">
                    <a href="editPage?playerId=${player.id}" target="iframe" class="btn btn-info">修改</a>
                    <a href="joinPage?playerId=${player.id}" target="iframe" class="btn btn-darkorange">加入球队</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Basic Scripts-->
<script src="../../resource/assets/js/jquery-2.0.3.min.js"></script>
<script src="../../resource/assets/js/bootstrap.min.js"></script>

<!--Beyond Scripts-->
<script src="../../resource/assets/js/beyond.min.js"></script>
<!--Page Related Scripts-->
<!--Jquery Select2-->
<script src="../../resource/assets/js/select2/select2.js"></script>
<!--Bootstrap Tags Input-->
<script src="../../resource/assets/js/tagsinput/bootstrap-tagsinput.js"></script>

<!--Bootstrap Date Picker-->
<script src="../../resource/assets/js/datetime/bootstrap-datepicker.js"></script>

<!--Bootstrap Time Picker-->
<script src="../../resource/assets/js/datetime/bootstrap-timepicker.js"></script>

<!--Fuelux Spinner-->
<script src="../../resource/assets/js/fuelux/spinner/fuelux.spinner.min.js"></script>

<script src="../../resource/assets/js/toastr/toastr.js"></script>
<!--Common Scripts -->
<script src="../../resource/js/commons.js"></script>
</body>
<!--  /Body -->
</html>